project_name: omnibump
version: 2

before:
  hooks:
    - go mod download

env:
  - COSIGN_YES=true

builds:
  - id: omnibump-build
    binary: omnibump
    main: ./
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - "386"
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
    flags:
      - -trimpath
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -extldflags "-static"
      - -X sigs.k8s.io/release-utils/version.gitVersion={{ .Version }}
      - -X sigs.k8s.io/release-utils/version.gitCommit={{ .Commit }}
      - -X sigs.k8s.io/release-utils/version.gitTreeState=clean
      - -X sigs.k8s.io/release-utils/version.buildDate={{ .CommitDate }}

signs:
  - id: omnibump-cosign
    cmd: cosign
    certificate: "${artifact}.crt"
    args:
      [
        "sign-blob",
        "--output-signature",
        "${signature}",
        "--output-certificate",
        "${certificate}",
        "${artifact}",
        "--yes",
      ]
    artifacts: all

archives:
  - files:
      - LICENSE
    wrap_in_directory: true

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  draft: false
  name_template: "Release {{ .Tag }}"
